services:
  api:
    container_name: withdraw-pix-api
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    depends_on:
      - rabbitmq
    networks:
      - withdraw-pix-api

  mysql:
    build: ./.docker/mysql
    container_name:  withdraw-pix-db
    restart: always
    tty: true
    ports:
      - 33006:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=withdraw_pix
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - withdraw-pix-api

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - withdraw-pix-api

  mailhog:
    image: mailhog/mailhog
    container_name: withdraw-pix-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - withdraw-pix-api

  redis:
    container_name: withdraw-pix-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - withdraw-pix-api

networks:
  withdraw-pix-api:
    driver: bridge
